name: perf_test

on: 
  push:
  pull_request:


jobs:
  
  window_test:
    name: Windows
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: |
        .\run_test.bat
        
        
  linux_test:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test
      shell: bash
      run: |
        sh run_test.sh

  mac_test:
    name: Mac
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    - name: Test
      shell: bash
      run: |
        sh run_test.sh